import { nanoid } from 'nanoid';

export default [
  {
    id: nanoid(),
    date: 'April 1',
    rating: 77,
    emotions: [
      { icon: '😊', text: 'Satisifed' },
      { icon: '☺️', text: 'Relaxed' },
      { icon: '🙏', text: 'Grateful' },
      { icon: '️️️⚡️', text: 'Energetic' },
    ],
    activities: [
      { icon: '🏃‍♂️', text: 'Running' },
      { icon: '️️️🧘‍♂️', text: 'Meditation' },
      { icon: '️✍️', text: 'Journaling' },
      { icon: '️📖', text: 'Reading' },
      { icon: '️👨‍👩‍👦‍👦', text: 'Family Time' },
    ],
    note: `Nothing very exciting happened, but today was a pretty nice day! I had a good balance of "me time" and family time, and I felt very relaxed and satisfied by the end of it.`,
  },
  {
    id: nanoid(),
    date: 'April 2',
    rating: 96,
    emotions: [
      { icon: '😇', text: 'Proud' },
      { icon: '🥰', text: 'Appreciated' },
      { icon: '😃', text: 'Joyful' },
      { icon: '️🥳', text: 'Celebratory' },
    ],
    activities: [
      { icon: '🏆', text: 'Personal Victory' },
      { icon: '️️️💪', text: 'Personal Growth' },
      { icon: '️🍛', text: 'Good Meal' },
      { icon: '️🛌', text: 'Good Sleep' },
      { icon: '️👨‍👩‍👦‍👦', text: 'Family Time' },
    ],
    note: "I finally finished my big work project that I've been working on for the past three months, and I feel like I've really improved myself as a member of my team. My colleagues all said I did a really good job! My family and I went out for dinner to celebrate.",
  },
  {
    id: nanoid(),
    date: 'April 3',
    rating: 44,
    emotions: [
      { icon: '😃', text: 'Excited' },
      { icon: '🤞', text: 'Hopeful' },
      { icon: '😞', text: 'Disappointed' },
      { icon: '️😱', text: 'Shocked' },
      { icon: '😵‍💫', text: 'Confused' },
      { icon: '🎢', text: 'Emotional Roller Coaster' },
    ],
    activities: [
      { icon: '⬅️', text: 'Personal Setback' },
      { icon: '️️️‍👨‍💻', text: 'Work Problems' },
      { icon: '️🍽', text: 'Missed Meal' },
      { icon: '️🥱', text: 'Bad Sleep' },
    ],
    note: `After yesterday's success, I went to work today hoping I'd finally get the big promotion I've been waiting for — but instead, my boss told me I still had "room for improvement" and said he wasn't satisfied with a lot of the work I've done this year. I got the sense that he was closer to wanting to fire me than promote me.`,
  },
  {
    id: nanoid(),
    date: 'April 4',
    rating: 28,
    emotions: [
      { icon: '😤', text: 'Resentful' },
      { icon: '😡', text: 'Angry' },
      { icon: '😬', text: 'Anxious' },
      { icon: '☹️', text: 'Sad' },
      { icon: '🌪', text: 'Turbulent' },
      { icon: '️😴', text: 'Tired' },
    ],
    activities: [
      { icon: '🛋', text: 'Sitting Around' },
      { icon: '️️️‍📺', text: 'Watching TV' },
      { icon: '️🎮', text: 'Gaming' },
      { icon: '️🍺', text: 'Drinking' },
    ],
    note: `I didn't do anything productive and didn't take care of myself today. I just "let myself go" and tried to distract myself. The more I think about what happened at work yesterday, the worse I feel about it.`,
  },
  {
    id: nanoid(),
    date: 'April 5',
    rating: 12,
    emotions: [
      { icon: '😥', text: 'Tearful' },
      { icon: '😫', text: 'Upset' },
      { icon: '😬', text: 'Worried' },
      { icon: '😧', text: 'Scared' },
    ],
    activities: [
      { icon: '🍩', text: 'Eating Junk Food' },
      { icon: '️️️‍📱', text: 'Pointless Scrolling' },
      { icon: '️🚬', text: 'Smoking' },
      { icon: '️🍺', text: 'Drinking' },
    ],
    note: `I felt even worse and "let myself go" even further today. I even smoked for the first time in months. I'm in a downward spiral. I need to pull myself out of it tomorrow `,
  },
  {
    id: nanoid(),
    date: 'April 6',
    rating: 42,
    emotions: [
      { icon: '😐', text: 'Serious' },
      { icon: '🧐', text: 'Self-Critical' },
      { icon: '🙄', text: 'Ashamed' },
      { icon: '🫡', text: 'Resolute' },
    ],
    activities: [
      { icon: '🏃‍♂️', text: 'Running' },
      { icon: '️️️🧘‍♂️', text: 'Meditation' },
      { icon: '️️️🏋️‍♀️', text: 'Weight Lifting' },
      { icon: '️️️🥗', text: 'Healthy Eating' },
      { icon: '️️️💭', text: 'Self-Reflection' },
    ],
    note: `I woke up feeling ashamed of myself for how I've been acting the last couple of days. I decided today would be the day I started turning things around. I did a lot of self-reflection, I took care of myself, and I felt a bit better by the end of the day. I'll try to carry on in the same way tomorrow.`,
  },
  {
    id: nanoid(),
    date: 'April 7',
    rating: 64,
    emotions: [
      { icon: '💪', text: 'Strong' },
      { icon: '🤨', text: 'Uncertain' },
      { icon: '🤔', text: 'Pensive' },
    ],
    activities: [
      { icon: '🚴‍♀️', text: 'Biking' },
      { icon: '️️️🚶', text: 'Walking' },
      { icon: '️️️🥗', text: 'Healthy Eating' },
      { icon: '️️️💭', text: 'Self-Reflection' },
    ],
    note: `I did some more reflection today, and I realized something: I don't think my boss is actually dissatisfied with my work. I think he just doesn't like me. But if that's true, what should I do? Doesn't it mean I'm in a dead-end job?`,
  },
  {
    id: nanoid(),
    date: 'April 8',
    rating: 84,
    emotions: [
      { icon: '😌', text: 'Calm' },
      { icon: '🫡', text: 'Resolute' },
      { icon: '😎', text: 'Decisive' },
    ],
    activities: [
      { icon: '🥾', text: 'Hiking' },
      { icon: '️️️💭', text: 'Self-Reflection' },
      { icon: '️️️❗️', text: 'Big Decision' },
    ],
    note: `I went to the woods for a hike today. I did some more thinking there, and I came to a big decision: I *am* in a dead-end job, and I haven't been enjoying it for a long time — so I should quit! I'm going to hand in my notice tomorrow.`,
  },
  {
    id: nanoid(),
    date: 'April 9',
    rating: 65,
    emotions: [
      { icon: '😮‍💨', text: 'Relieved' },
      { icon: '😬', text: 'Worried' },
      { icon: '😊', text: 'Happy' },
      { icon: '😢', text: 'Sad' },
      { icon: '😡', text: 'Angry' },
      { icon: '🎢', text: 'Emotional Roller Coaster' },
    ],
    activities: [
      { icon: '🚨', text: 'Big Event' },
      { icon: '️️️🔚', text: 'End of an Era' },
      { icon: '️️️🆕', text: 'New Beginning' },
      { icon: '️️️🥊', text: 'Boxing' },
      { icon: '️️️🏋️‍♀️', text: 'Weight Lifting' },
    ],
    note: `I did it! I quit! I handed in my notice, and my boss said I could just go ahead, collect my things, and leave right away. He didn't want me around for the next two weeks. He was quite a jerk about it, to be honest. I'm glad I made my decision, and it's a relief to know I won't have to go back to a job I don't like. But I will miss some of my colleagues, and I feel a bit worried about what I'm going to do next. I probably should have found a new job before quitting this one. I did some boxing and weight lifting to blow off steam.`,
  },
  {
    id: nanoid(),
    date: 'April 10',
    rating: 41,
    emotions: [
      { icon: '🤯', text: 'Mind Blown' },
      { icon: '😲', text: 'Shocked' },
      { icon: '😭', text: 'Upset' },
    ],
    activities: [
      { icon: '💻', text: 'Job Hunting' },
      { icon: '️️️📞', text: 'Making Calls' },
      { icon: '️️️👎', text: 'Experiencing Rejection' },
    ],
    note: `I made some calls to people I know in my industry, and I looked at all of the open positions in my area on the main job websites. I applied to a few of them, but there are very few positions available. I'm shocked at how bad the job market is. One hiring manager told me he got 150 applicants for a low-paying position they just filled. I got a couple of responses back already, and they were all negative.`,
  },
  {
    id: nanoid(),
    date: 'April 11',
    rating: 22,
    emotions: [
      { icon: '😬', text: 'Anxious' },
      { icon: '😭', text: 'Upset' },
      { icon: '😧', text: 'Afraid' },
      { icon: '😫', text: 'Regretful' },
    ],
    activities: [
      { icon: '💻', text: 'Job Hunting' },
      { icon: '️️️👎', text: 'Experiencing Rejection' },
      { icon: '️🍺', text: 'Drinking' },
      { icon: '️🚬', text: 'Smoking' },
    ],
    note: `More rejection. No luck at all with the job hunt. Now I'm getting scared — what if I don't find a new job? I really shouldn't have quit my old job so hastily. I should have thought things through more and not been so impulsive. I think I made a big mistake.`,
  },

  {
    id: nanoid(),
    date: 'April 12',
    rating: 17,
    emotions: [
      { icon: '😭', text: 'Despondent' },
      { icon: '😱', text: 'Horrified' },
    ],
    activities: [
      { icon: '🛏', text: 'Lying in Bed' },
      { icon: '️️️💦', text: 'Crying' },
    ],
    note: `Today I completely fell apart. I just stayed in bed all day and cried. I don't think I can find a new job, and I don't know how I'm going to make ends meet. `,
  },

  {
    id: nanoid(),
    date: 'April 13',
    rating: 6,
    emotions: [
      { icon: '😶', text: 'Numb' },
      { icon: '🏳', text: 'Giving Up' },
    ],
    activities: [
      { icon: '🍨', text: 'Eating Ice Cream' },
      { icon: '🍰', text: 'Eating Cake' },
    ],
    note: `Same as yesterday, only now I somehow feel even worse. The main thing I did was eat ice cream and cake. This is just who I am now, I guess — a person with no job and no income, who just sits around and eats cake and ice cream all day. `,
  },

  {
    id: nanoid(),
    date: 'April 14',
    rating: 100,
    emotions: [
      { icon: '☺️', text: 'Joy' },
      { icon: '😅', text: 'Relief' },
      { icon: '🥳', text: 'Celebratory' },
      { icon: '🤩', text: 'Star-struck' },
    ],
    activities: [
      { icon: '🎁', text: 'Received Unexpected Gift' },
      { icon: '️️️🍀', text: 'Got lucky' },
      { icon: '️️️🎉', text: 'New Beginning' },
      { icon: '️️️👽', text: 'Paranormal Activity' },
    ],
    note: `Something totally unexpected happened today! I woke up this morning still feeling horrible, and after lying in bed for a few hours, I decided to get up to get some more cake. But when I entered the kitchen, I saw something unbelievable: three aliens standing in front of my refrigerator! They said, "We come in peace — but you cannot eat another piece of cake. We are here to take you away, to a better world." And then they beamed me up to their ship. We blasted away from Earth, entered a wormhole, and were on the other side of the galaxy in just a couple of minutes. We then landed on their planet, Gorzarg 7, where I was met with yet another surprise: on planet Gorzarg 7, the highly advanced society has instituted a universal basic income, and most work has been automated by AI-powered robots! I never need to worry about a job again! What a fantastic way to end the week!`,
  },
];
